/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package finalprojects;

import javax.swing.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        SwingUtilities.invokeLater(() -> {
            MemberManager memberManager = new MemberManager();
            // Ask user to input username
            String username = JOptionPane.showInputDialog(null, "Enter your username:");

            // If username is not empty and user clicked OK
            if (username != null && !username.isEmpty()) {
                UserData.getInstance().setUsername(username);
                // Switch to main frame
                MainFrame mainFrame = new MainFrame(memberManager);
                mainFrame.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Username input cancelled. Exiting application.", "Error", JOptionPane.ERROR_MESSAGE);
                System.exit(1);
            }
        });

        // SwingUtilities.invokeLater(new Runnable() {
        //     @Override
        //     public void run() {
        //         FinReporting frame = new FinReporting();
        //         frame.setVisible(true);
        //     }
        // });
    }
}
